### ISSUE TITLE
What is result type?

### ISSUE THREAD

**Issue by agn-7** [ferencberes/twitter-crawler#7]
Hello

Yesterday I was acquainted with this repo for crawling tweets and I found out that `recursive_crawling` is my purpose. However, I'm confused about some configurations and parameters and I couldn't find the respective answer in your documentation so far.

For example, what is the `result_type: recent`?

```
search_params = {
    "q":"#bitcoin OR #ethereum OR blockchain OR crypto",
    "result_type":"recent",
    "lang":"en",
    "count":100
}
```

Thanks in advance.

**Comment by ferencberes** [comment]
Hello

It is an argument of the Twitter Search API, whether the API should return recent or popular tweets for your query. 
You can find the details here: 
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets

I hope it answers your question.

Best,
Ferenc

**Comment by agn-7** [comment]
Thanks for your response. I didn't know about that.
